version: '3'

services:
  master:
    image: gettyimages/spark:2.0.2-hadoop-2.7
    command: bin/spark-class org.apache.spark.deploy.master.Master
    networks:
      - spark
    ports:
      - 8080:8080
      - 7077:7077
      - 6066:6066
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s

  worker:
    image: gettyimages/spark:2.0.2-hadoop-2.7
    command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
    networks:
      - spark
    deploy:
      replicas: 1
      placement:
        constraints: [node.role != manager]
      update_config:
        parallelism: 1
        delay: 10s

networks:
  spark:
    external: true
