version: '3'

services:
  spark-master:
    image: fsoppelsa/spark-master
    networks:
      - spark
    ports:
      - 8080:8080
      - 7077:7077
      - 6066:6066
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      update_config:
        parallelism: 1
        delay: 10s

  spark-worker:
    image: fsoppelsa/spark-worker
    networks:
      - spark
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
      update_config:
        parallelism: 1
        delay: 10s

networks:
  spark:
    external: true
